import Navbar from '@/components/navbar/Navbar'
import './globals.scss'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Emma Pierre Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <div className="layoutContainer">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
